# -*- coding: utf-8 -*-
"""Intotogeopanda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NEK8wbaZODyL29A7LWmnpAfJQke0VXwP
"""

!pip install geopandas

#importing  an ESRI Shapefile and plotting it using Geopandas

import geopandas as gpd
import matplotlib.pyplot as plt

districts = gpd.read_file("/content/ke_subcounty.zip")

districts

type(districts)

districts.plot(cmap = 'hsv', edgecolor = 'black', column = 'subcounty')

country = gpd.read_file('/content/ken_admbnda_adm0_iebc_20180607.zip')
atmspoint = gpd.read_file('/content/hotosm_ken_financial_services_points_shp.zip')
atmspolygon = gpd.read_file('/content/hotosm_ken_financial_services_polygons_shp.zip')
migori = gpd.read_file('/content/migori.zip')

country

country.plot()

#ploting figures side by side

fig, (ax1, ax2, ax3, ax4, ax5) = plt.subplots(ncols = 5, figsize = (12, 10))
districts.plot(ax = ax1, cmap = 'hsv', edgecolor = 'black', column = 'subcounty')
country.plot(ax = ax2, color = 'green', edgecolor = 'black')
atmspoint.plot(ax = ax3, color = 'red', edgecolor = 'black')
atmspolygon.plot(ax = ax4, color = 'blue', edgecolor = 'black')
migori.plot(ax = ax5)

"""Plotting multiple layers on top of another"""

districts.crs

fig, ax = plt.subplots(figsize = (10, 12))
districts.plot(ax = ax, cmap = 'Spectral', edgecolor = 'black', column = 'subcounty')
migori.plot(ax = ax, color = 'red', edgecolor = 'black')

"""Reprojecvting Geopandas GeodataFrames"""

fig, ax = plt.subplots(figsize = (10, 12))
district = districts.to_crs(epsg = 32629)
district.plot(ax = ax, figsize = (10,8), cmap = 'hsv', edgecolor = 'black', column = 'subcounty')
migori = migori.to_crs(epsg = 32629)
migori.plot(ax = ax, figsize = (10,8), color = 'none', edgecolor = 'black')

"""  Intersecting layers"""

district_migori = gpd.overlay(district, migori, how = 'intersection')

district_migori.plot()